# Generated by Django 2.1 on 2018-08-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_install', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('full_address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FusionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('google_id', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('google_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_install.GoogleUser')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='fusion_table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps_main.FusionTable'),
        ),
        migrations.AddField(
            model_name='address',
            name='google_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_install.GoogleUser'),
        ),
    ]
